Feature/sp 257
Knawat/zoho-finance pull request #1
Opened 2021-07-02 05:30 UTC by neer14

## :memo: Description

Add .github folder

2021-07-04 08:06 UTC, HazemKhaled requested changes

2021-07-04 08:06 UTC, HazemKhaled commented on package.json
> +    "@knawat/types": "^1.1.25",
Why Knawat Types into Zoho Finance? should be a generic Zoho package, while transforming to Knawat's format into Knawat's app

2021-07-26 07:10 UTC, neer14 commented on package.json
> +    "@knawat/types": "^1.1.25",
removed knawat/types

2021-08-12 15:48 UTC, HazemKhaled approved these changes

2021-08-12 15:48 UTC, merged